### ISSUE TITLE
Number of transcripts per subject

### ISSUE THREAD

**Issue by BobGently** [juliema/label_reconciliations#54]
Hello

I would like to make use of your code for the Reading Natures Library project for Manchester Museum

There appears to be a constraint to only read 3 transcriptions per subject, can you point me to where that is coded so we can test with larger numbers?

Regards
Bob

**Comment by rafelafrance** [comment]
I don't have a lot of time to work on this for the next few weeks but one thing for you to explore in the interim is the [KEEP_COUNT in nfn.py](https://github.com/juliema/label_reconciliations/blob/master/lib/formats/nfn.py#L12). If this turns out to work for you then we can look into making it a command-line option.

**Comment by denslowm** [comment]
@BobGently As an aside, I would be curious to know why you are using 15 transcriptions per subject. We have done some work with Fossils and other kinds of specimen types. A retirement limit of 3 works well for the vast majority though we have used 5 in rare cases.

**Comment by rafelafrance** [comment]
Make --keep-count N a command line option
